import { useEffect, useMemo, useState } from "react";
import "@/App.css";
import "@/responsive.css";
import { BookOpen, CalendarDays, ChevronRight, CircleUserRound, Clock3, FileText, Grid2X2, LogIn, Menu, Search, ShieldCheck, Sparkles, Users, X } from "lucide-react";

const coverBase = "https://images.unsplash.com/";
const APPS_SCRIPT_URL = process.env.REACT_APP_APPS_SCRIPT_URL;
const gasRequest = async (action, payload = {}) => {
  if (!APPS_SCRIPT_URL) return null;
  const response = await fetch(APPS_SCRIPT_URL, { method: "POST", body: JSON.stringify({ action, ...payload }) });
  return response.json();
};
const books = [
  { id: 1, title: "Pendidikan Karakter di Era Digital", author: "Dr. Nurul Hidayati", type: "Buku", category: "Pendidikan", year: "2024", stock: 4, cover: `${coverBase}photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=85`, featured: true },
  { id: 2, title: "Metodologi Penelitian Kualitatif", author: "Prof. Budi Santoso", type: "Buku", category: "Metodologi", year: "2023", stock: 2, cover: `${coverBase}photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=800&q=85`, featured: true },
  { id: 3, title: "Transformasi Pembelajaran Berbasis Teknologi", author: "Rina Kartika, M.Pd.", type: "E-Book", category: "Teknologi", year: "2024", stock: 8, cover: `${coverBase}photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=85`, featured: true },
  { id: 4, title: "Ekologi Pesisir Jawa Timur", author: "Ahmad Fauzi", type: "Skripsi", category: "Sains", year: "2022", stock: 1, cover: `${coverBase}photo-1532012197267-da84d127e765?auto=format&fit=crop&w=800&q=85` },
  { id: 5, title: "Literasi Informasi Mahasiswa", author: "Dewi Anggraini", type: "Jurnal", category: "Literasi", year: "2024", stock: 6, cover: `${coverBase}photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=800&q=85` },
  { id: 6, title: "Pengantar Ilmu Komunikasi", author: "Yusuf Pratama", type: "Buku", category: "Sosial", year: "2021", stock: 0, cover: `${coverBase}photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=85` },
];

const loanSeed = [{ bookId: 1, title: "Pendidikan Karakter di Era Digital", date: "12 Mar 2025", due: "26 Mar 2025", status: "Sedang dipinjam" }];

function App() {
  const [page, setPage] = useState("home");
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("Semua kategori");
  const [selected, setSelected] = useState(null);
  const [loggedIn, setLoggedIn] = useState(false);
  const [showLogin, setShowLogin] = useState(false);
  const [mobileNav, setMobileNav] = useState(false);
  const [loans, setLoans] = useState(loanSeed);
  const [reservations, setReservations] = useState([]);
  const filtered = useMemo(() => books.filter(b => (category === "Semua kategori" || b.category === category) && `${b.title} ${b.author}`.toLowerCase().includes(query.toLowerCase())), [query, category]);
  const navigate = (next) => { setPage(next); setMobileNav(false); window.scrollTo({ top: 0, behavior: "smooth" }); };
  useEffect(() => { const status = document.querySelector('[data-testid="sync-status"]'); if (status) status.lastChild.textContent = APPS_SCRIPT_URL ? " Tersinkron dari Google Sheets" : " Mode demo lokal — Apps Script belum dihubungkan"; }, [page]);

  const borrow = async (book) => {
    if (!loggedIn) { setShowLogin(true); return; }
    if (book.stock === 0) { setReservations([...reservations, { title: book.title, position: reservations.length + 1, date: "Hari ini" }]); setSelected(null); await gasRequest("reserve", { bookId: book.id, memberId: "DL-24081" }); return; }
    setLoans([{ bookId: book.id, title: book.title, date: "Hari ini", due: "14 hari lagi", status: "Sedang dipinjam" }, ...loans]);
    await gasRequest("borrow", { bookId: book.id, memberId: "DL-24081" });
    setSelected(null);
  };
  const returnLoan = async (index) => { const loan = loans[index]; setLoans(loans.filter((_, i) => i !== index)); await gasRequest("return", { bookId: loan.bookId, memberId: "DL-24081" }); };

  return <div className="app-shell">
    <header className="topbar"><div className="topbar-inner">
      <button className="brand" data-testid="site-brand-button" onClick={() => navigate("home")}><span className="brand-mark"><BookOpen size={20} /></span><span><strong>DigiLib</strong><small>PERPUSTAKAAN DIGITAL</small></span></button>
      <button className="mobile-menu" data-testid="mobile-menu-button" onClick={() => setMobileNav(!mobileNav)}>{mobileNav ? <X /> : <Menu />}</button>
      <nav className={mobileNav ? "main-nav open" : "main-nav"} data-testid="main-navigation"><button className={page === "home" ? "nav-active" : ""} data-testid="nav-home-button" onClick={() => navigate("home")}>Beranda</button><button className={page === "catalog" ? "nav-active" : ""} data-testid="nav-catalog-button" onClick={() => navigate("catalog")}>Katalog</button><button data-testid="nav-repository-button" onClick={() => navigate("catalog")}>Repositori</button><button data-testid="nav-about-button" onClick={() => navigate("home")}>Tentang kami</button><button className={page === "admin" ? "nav-active" : ""} data-testid="nav-admin-button" onClick={() => navigate("admin")}>Admin</button></nav>
      <div className="header-actions">{loggedIn ? <button className="profile-chip" data-testid="profile-menu-button" onClick={() => navigate("profile")}><span className="avatar">AR</span><span>Andi R.</span></button> : <button className="login-link" data-testid="header-login-button" onClick={() => setShowLogin(true)}><LogIn size={17} /> Masuk</button>}</div>
    </div></header>

    {page === "home" && <main>
      <section className="hero"><div className="hero-content"><div className="eyebrow"><Sparkles size={15} /> RUANG BACA UNTUK SEMUA</div><h1>Temukan ide.<br /><em>Bangun masa depan.</em></h1><p>Jelajahi koleksi buku, skripsi, jurnal, dan karya ilmiah untuk menemani perjalanan belajarmu.</p><div className="hero-search"><Search size={20} /><input data-testid="hero-search-input" value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => e.key === "Enter" && navigate("catalog")} placeholder="Cari judul, penulis, atau topik..." /><button data-testid="hero-search-button" onClick={() => navigate("catalog")}>Cari koleksi</button></div><div className="search-hint"><span>Populer:</span><button data-testid="popular-topic-pendidikan" onClick={() => { setQuery("pendidikan"); navigate("catalog"); }}>Pendidikan</button><button data-testid="popular-topic-teknologi" onClick={() => { setQuery("teknologi"); navigate("catalog"); }}>Teknologi</button><button data-testid="popular-topic-literasi" onClick={() => { setQuery("literasi"); navigate("catalog"); }}>Literasi</button></div></div><div className="hero-art"><img src="https://images.unsplash.com/photo-1564910443496-5fd2d76b47fa?auto=format&fit=crop&w=1200&q=85" alt="Interior perpustakaan modern" /><div className="hero-stat"><strong>24.8K</strong><span>koleksi digital tersedia</span></div></div></section>
      <section className="stats-strip"><div><strong>24,836</strong><span>Total koleksi</span></div><div><strong>8,142</strong><span>Anggota aktif</span></div><div><strong>1,204</strong><span>Judul e-book</span></div><div><strong>98%</strong><span>Kepuasan anggota</span></div></section>
      <section className="section featured-section"><div className="section-heading"><div><span className="section-kicker">PILIHAN PUSTAKAWAN</span><h2>Koleksi pilihan minggu ini</h2></div><button className="text-link" data-testid="view-all-books-button" onClick={() => navigate("catalog")}>Lihat semua koleksi <ChevronRight size={17} /></button></div><div className="book-grid">{books.filter(b => b.featured).map(book => <BookCard key={book.id} book={book} onOpen={setSelected} />)}</div></section>
      <section className="member-banner"><div><span className="section-kicker">AKSES LEBIH BANYAK</span><h2>Jadikan membaca<br /><em>sebuah kebiasaan.</em></h2><p>Daftar sebagai anggota untuk meminjam koleksi, menyimpan buku favorit, dan melihat riwayat bacaanmu.</p></div><button data-testid="banner-register-button" onClick={() => setShowLogin(true)}>Mulai jadi anggota <ChevronRight size={17} /></button></section>
    </main>}

    {page === "catalog" && <main className="page-main"><div className="page-title"><div><span className="section-kicker">KOLEKSI DIGITAL</span><h1>Jelajahi pengetahuan</h1><p>Temukan koleksi yang relevan dengan kebutuhanmu.</p></div><div className="sync-status" data-testid="sync-status"><span></span> Tersinkron dari Google Sheets</div></div><div className="catalog-toolbar"><div className="catalog-search"><Search size={18} /><input data-testid="catalog-search-input" value={query} onChange={e => setQuery(e.target.value)} placeholder="Cari koleksi..." /></div><select data-testid="category-filter-select" value={category} onChange={e => setCategory(e.target.value)}>{["Semua kategori", "Pendidikan", "Metodologi", "Teknologi", "Sains", "Literasi", "Sosial"].map(c => <option key={c}>{c}</option>)}</select></div><div className="results-row"><span data-testid="catalog-result-count">Menampilkan <strong>{filtered.length}</strong> koleksi</span><button className="sort-button" data-testid="catalog-sort-button"><Grid2X2 size={16} /> Tampilan grid</button></div><div className="book-grid catalog-grid">{filtered.map(book => <BookCard key={book.id} book={book} onOpen={setSelected} />)}</div>{filtered.length === 0 && <div className="empty-state" data-testid="catalog-empty-state">Koleksi tidak ditemukan. Coba kata kunci lain.</div>}</main>}

    {page === "profile" && <main className="page-main profile-page"><div className="page-title"><div><span className="section-kicker">RUANG PRIBADI</span><h1>Halo, Andi.</h1><p>Kelola aktivitas dan koleksi bacaanmu di sini.</p></div></div><div className="profile-layout"><aside className="profile-card"><div className="profile-avatar">AR</div><h3>Andi Rachman</h3><span>Mahasiswa · 2025</span><div className="profile-divider" /><button className="profile-nav-active" data-testid="profile-overview-tab"><CircleUserRound size={17} /> Ringkasan akun</button><button data-testid="profile-history-tab"><Clock3 size={17} /> Riwayat peminjaman</button><button data-testid="profile-logout-button" onClick={() => { setLoggedIn(false); navigate("home"); }}>Keluar akun</button></aside><section className="profile-content"><div className="profile-welcome"><div><span className="section-kicker">AKTIVITASMU</span><h2>Ringkasan akun</h2></div><span className="member-code" data-testid="member-id">ID ANGGOTA · DL-24081</span></div><div className="mini-stats"><div><BookOpen size={19} /><strong>{loans.length}</strong><span>Buku dipinjam</span></div><div><CalendarDays size={19} /><strong>14</strong><span>Hari tersisa</span></div><div><FileText size={19} /><strong>12</strong><span>Riwayat selesai</span></div></div><div className="loan-box"><div className="loan-heading"><h3>Peminjaman aktif</h3><button className="text-link" data-testid="profile-browse-button" onClick={() => navigate("catalog")}>Cari buku <ChevronRight size={16} /></button></div>{loans.map((loan, i) => <div className="loan-row" data-testid={`active-loan-${i}`} key={`${loan.title}-${i}`}><div className="loan-icon"><BookOpen size={19} /></div><div><strong>{loan.title}</strong><span>Dipinjam {loan.date} · Jatuh tempo {loan.due}</span></div><span className="loan-status">{loan.status}</span><button className="return-button" data-testid={`return-loan-${i}`} onClick={() => returnLoan(i)}>Kembalikan</button></div>)}{reservations.length > 0 && <div className="reservation-list" data-testid="reservation-list"><h3>Antrean reservasi</h3>{reservations.map((item, i) => <div className="reservation-row" data-testid={`reservation-item-${i}`} key={`${item.title}-${i}`}><span className="queue-number">{item.position}</span><div><strong>{item.title}</strong><span>Permintaan {item.date} · FIFO</span></div><span className="queue-status">Menunggu</span></div>)}</div>}</div></section></div></main>}

    {page === "admin" && <AdminPanel books={books} />}
    <footer><div className="footer-brand"><span className="brand-mark"><BookOpen size={18} /></span><strong>DigiLib</strong></div><span>Perpustakaan digital Universitas Negeri Surabaya</span><span>© 2025 DigiLib</span></footer>
    {selected && <BookDetail book={selected} onClose={() => setSelected(null)} onBorrow={() => borrow(selected)} loggedIn={loggedIn} />}
    {showLogin && <LoginModal onClose={() => setShowLogin(false)} onLogin={() => { setLoggedIn(true); setShowLogin(false); setSelected(null); }} />}
  </div>;
}

function BookCard({ book, onOpen }) { return <article className="book-card" data-testid={`book-card-${book.id}`}><button className="book-cover" data-testid={`book-open-${book.id}`} onClick={() => onOpen(book)}><img src={book.cover} alt={`Sampul ${book.title}`} /><span className="book-type">{book.type}</span></button><div className="book-info"><span className="book-category">{book.category}</span><h3>{book.title}</h3><p>{book.author}</p><div className="book-meta"><span>{book.year}</span><span className={book.stock ? "available" : "unavailable"}>{book.stock ? `${book.stock} tersedia` : "Sedang dipinjam"}</span></div></div></article> }
function BookDetail({ book, onClose, onBorrow, loggedIn }) { return <div className="modal-backdrop" data-testid="book-detail-modal"><div className="detail-modal"><button className="modal-close" data-testid="book-detail-close-button" onClick={onClose}><X /></button><img className="detail-cover" src={book.cover} alt={`Sampul ${book.title}`} /><div className="detail-copy"><span className="book-category">{book.category} · {book.type}</span><h2>{book.title}</h2><p className="detail-author">Oleh {book.author}</p><div className="detail-meta"><span><CalendarDays size={16} /> Terbit {book.year}</span><span><FileText size={16} /> Bahasa Indonesia</span></div><p className="abstract">Buku ini menghadirkan pembahasan terstruktur dan kontekstual untuk mendukung proses belajar, penelitian, dan pengembangan wawasan pembaca.</p><button className="primary-button" data-testid="borrow-book-button" onClick={onBorrow}>{book.stock === 0 ? "Masuk antrean reservasi" : loggedIn ? "Pinjam koleksi" : "Masuk untuk meminjam"} <ChevronRight size={17} /></button></div></div></div> }
function LoginModal({ onClose, onLogin }) { return <div className="modal-backdrop" data-testid="login-modal"><div className="login-modal"><button className="modal-close" data-testid="login-close-button" onClick={onClose}><X /></button><div className="login-icon"><ShieldCheck size={25} /></div><span className="section-kicker">AKSES ANGGOTA</span><h2>Selamat datang kembali</h2><p>Masuk untuk meminjam koleksi dan mengelola aktivitas bacaan.</p><label>Email anggota<input data-testid="login-email-input" type="email" placeholder="nama@unesa.ac.id" /></label><label>Kata sandi<input data-testid="login-password-input" type="password" placeholder="••••••••" /></label><button className="primary-button full" data-testid="login-submit-button" onClick={onLogin}>Masuk ke DigiLib <ChevronRight size={17} /></button><small>Demo: klik masuk untuk mencoba sebagai Andi Rachman</small></div></div> }
function AdminPanel({ books: catalog }) { return <main className="page-main admin-page"><div className="page-title"><div><span className="section-kicker">PUSAT KENDALI</span><h1>Panel admin</h1><p>Kelola katalog dan aktivitas perpustakaan dalam satu tempat.</p></div><button className="primary-button" data-testid="admin-add-book-button">+ Tambah koleksi</button></div><div className="admin-stats"><div><BookOpen /><strong>{catalog.length}</strong><span>Total koleksi</span></div><div><Users /><strong>8,142</strong><span>Anggota aktif</span></div><div><Clock3 /><strong>126</strong><span>Peminjaman aktif</span></div><div><ShieldCheck /><strong>99.8%</strong><span>Sinkronisasi</span></div></div><section className="admin-table-card"><div className="table-heading"><h2>Katalog terbaru</h2><button className="text-link" data-testid="admin-manage-catalog-button">Kelola katalog <ChevronRight size={16} /></button></div><div className="admin-table">{catalog.slice(0, 5).map(book => <div className="table-row" data-testid={`admin-book-row-${book.id}`} key={book.id}><img src={book.cover} alt="" /><div><strong>{book.title}</strong><span>{book.author}</span></div><span>{book.category}</span><span>{book.stock} tersedia</span><button data-testid={`admin-edit-book-${book.id}`}>Edit</button></div>)}</div></section></main> }

export default App;